[package]
name = "hotg-rune-proc-blocks"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1.9.1"
getrandom = { version = "0.2.6", default-features = false, features = ["custom"], optional = true }
ndarray = "0.15.4"
thiserror = "1.0.31"
tracing = { version = "0.1.35", default-features = false, features = ["std"] }
tracing-subscriber = { version = "0.3.11", default-features = false, features = ["registry", "tracing-log"] }
wit-bindgen-rust = { git = "https://github.com/wasmerio/wit-bindgen", branch = "wasmer", version = "0.1.0", optional = true }

[features]
default = ["guest"]
guest = ["wit-bindgen-rust", "getrandom"]
