[package]
name = "hotg-rune-proc-blocks"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.4"
once_cell = "1.12.0"
rand = { version = "0.8.5", features = ["small_rng"] }
wit-bindgen-rust = { git = "https://github.com/bytecodealliance/wit-bindgen", optional = true }
getrandom = { version = "0.2.6", default-features = false, features = ["custom"] }

[features]
default = []
runtime_v1 = ["wit-bindgen-rust"]
