[package]
name = "hotg-rune-proc-blocks"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.4"
wit-bindgen-rust = { git = "https://github.com/bytecodealliance/wit-bindgen", optional = true }

[features]
default = ["runtime_v1"]
runtime_v1 = ["wit-bindgen-rust"]
