[workspace]
members = [
    "fft",
    "audio_float_conversion",
    "image-normalization",
    "label",
    "modulo",
    "most_confident_indices",
    "noise-filtering",
    "normalize",
    "utf8_decode",
    "parse",
    "segment_output",
    "tokenizers",
    "softmax",
    "argmax",
    "text_extractor",
    "binary_classification",
    "object_filter",
    "xtask"
]

# Temporary override while waiting for a fix to be merged upstream.
# See https://github.com/bytecodealliance/wit-bindgen/pull/184
[patch.'https://github.com/bytecodealliance/wit-bindgen']
wit-bindgen-rust = { git = "https://github.com/hotg-ai/wit-bindgen", branch = "variant-should-be-clone" }
wit-bindgen-wasmtime = { git = "https://github.com/hotg-ai/wit-bindgen", branch = "variant-should-be-clone" }
