[workspace]
members = [
    "fft",
    "audio_float_conversion",
    "image-normalization",
    "label",
    "modulo",
    "most_confident_indices",
    "noise-filtering",
    "normalize",
    "utf8_decode",
    "parse",
    "segment_output",
    "tokenizers",
    "softmax",
    "argmax",
    "text_extractor",
    "binary_classification",
    "object_filter",
    "xtask"
]

[patch."https://github.com/bytecodealliance/wit-bindgen"]
wit-bindgen-wasmtime = { git = "https://github.com/hotg-ai/witx-bindgen", rev = "44ae890c8cd8af47080a1802b5ddc09c9f61d442" }
