[workspace]
members = [
    "fft",
    "audio_float_conversion",
    "image-normalization",
    "label",
    "modulo",
    "most_confident_indices",
    "noise-filtering",
    "normalize",
    "utf8_decode",
    "parse",
    "segment_output",
    "tokenizers",
    "softmax",
    "argmax",
    "text_extractor",
    "binary_classification",
    "object_filter"
]

