[workspace]
members = [
    "fft",
    "audio_float_conversion",
    "image-normalization",
    "label",
    "modulo",
    "most_confident_indices",
    "noise-filtering",
    "normalize",
    "utf8_decode",
    "parse",
    "segment_output",
    "tokenizers",
    "softmax",
    "argmax",
    "text_extractor",
]

# Temporarily use the hotg-* crates from GitHub
[patch.crates-io]
hotg-rune-core = { git = "https://github.com/hotg-ai/rune", branch = "arguments-are-strings" }
hotg-rune-proc-blocks = { git = "https://github.com/hotg-ai/rune", branch = "arguments-are-strings" }
hotg-rune-proc-block-macros = { git = "https://github.com/hotg-ai/rune", branch = "arguments-are-strings" }
