[package]
name = "label"
version = "0.11.3"
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libm = {version = "0.2.1", default-features = false}
hotg-rune-proc-blocks = "^0.11.0"
line-span = "0.1.3"
