[package]
name = "logistic_regression"
version = "0.12.0"
edition = "2018"
description = "a statistical model that models the probability of one event taking place by having the log-odds for the event be a linear combination of one or more independent variables."
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hotg-rune-proc-blocks = { path = "../support" }
wit-bindgen-rust = { git = "https://github.com/bytecodealliance/wit-bindgen" }
linfa = "0.3.1"
linfa-logistic = "0.3.1"
linfa-datasets = { version = "0.3.1", features = ["winequality"] }


[lib]
crate-type = ["cdylib", "rlib"]

[package.metadata.wapm]
namespace = "hotg-ai"
abi = "none"
