[package]
name = "tokenizers"
version = "0.11.2"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
hotg-rune-proc-blocks = "^0.11.0"
anyhow = { version = "1.0", default-features = false }
unicode-normalization = {version = "0.1.19", default-features =false}
