[package]
name = "noise-filtering"
version = "0.8.0"
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hotg-rune-proc-blocks = "^0.8.0"
libm = "0.2.1"
paste = "1.0.5"
