[package]
name = "audio_float_conversion"
version = "0.0.0"
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hotg-rune-proc-blocks = "^0.11.0"

[dev-dependencies]
pretty_assertions = "0.7.2"
