[package]
name = "fft"
version = "0.12.0"
authors = ["The Rune Developers <developers@hotg.ai>"]
edition = "2018"
publish = false
repository = "https://github.com/hotg-ai/proc-blocks"
description = "converts a signal from its original domain (often time or space) to a representation in the frequency domain."

[lib]
crate-type = ["cdylib", "rlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hotg-rune-proc-blocks = { path = "../support" }
wit-bindgen-rust = { git = "https://github.com/bytecodealliance/wit-bindgen"}
hound = "3.4"
libm = "0.2.1"
# See https://github.com/hotg-ai/rune/pull/107#issuecomment-825806000
mel = { git = "https://github.com/hotg-ai/mel", rev = "017694ee3143c11ea9b75ba6cd27fe7c8a69a867", default-features = false }
nalgebra = { version = "0.29", default-features = false, features = ["alloc"] }
normalize = { path = "../normalize", version = "^0.12.0"}
sonogram = {git = "https://github.com/hotg-ai/sonogram", rev = "009bc0cba44267d8a0807e43c9bb0712f0f334ea" }

[dev-dependencies]
pretty_assertions = "0.7.2"

[package.metadata.wapm]
namespace = "hotg-ai"
abi = "none"

