name: Continuous integration

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  check:
    name: Compile and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - nightly
          - stable
          # MSRV - Required for std::process::Command's get_program() method
          - 1.57.0
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/cache@v1
        with:
          path: |
            ~/.cargo
            target/
            Cargo.lock
          key: ${{ runner.os }}-cargo-${{ matrix.rust }}
      - name: Setup Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          target: wasm32-unknown-unknown
      - run: ls -la */*
      - name: Type Checking
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all --verbose
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all --verbose
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all --verbose
      - name: Compile to WebAssembly
        uses: actions-rs/cargo@v1
        with:
          command: xtask
          args: dist --out-dir target/proc-blocks
      - name: Save Compiled proc-blocks
        uses: actions/upload-artifact@v2
        with:
          name: compiled-proc-blocks
          path: target/proc-blocks
      # Deploy the compiled proc-blocks to S3
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        if: github.ref == 'refs/heads/master'
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Upload compiled proc-blocks to S3
        run: aws s3 sync target/proc-blocks s3://assets.hotg.ai/proc-blocks
        if: github.ref == 'refs/heads/master'
      - name: Invalidate Cloudfront
        run: aws cloudfront create-invalidation --distribution-id=E20FU757GIUYVT --paths="/proc-blocks/*"
        if: github.ref == 'refs/heads/master' && matrix.rust == 'stable'

  api-docs:
    name: Publish API Docs to GitHub Pages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - nightly
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --all --verbose
      - name: Redirect top-level GitHub Pages
        run: "echo '<meta http-equiv=\"refresh\" content=\"0; url=proc_blocks/index.html\" />' > target/doc/index.html"
        shell: bash
      - name: Upload API Docs
        uses: JamesIves/github-pages-deploy-action@4.1.1
        if: github.ref == 'refs/heads/master'
        with:
          branch: gh-pages
          folder: target/doc
